### PR TITLE
Basically NASA

### PR DESCRIPTION
**Pull request by lukebrooker**
Add the new [webpack-dashboard](https://github.com/FormidableLabs/webpack-dashboard) hotness for better build transparency.

### CODE REVIEW

**Comment by bradparker** [comment]
This is super close. We might want to remove the progress plugin from the client config when running the dev server. Mine gets weird when both are running:

screen shot 2016-08-17 at 9 31 04 am

**Comment by bradparker** [comment]
Might be an idea to only include the progress plugin when running the "build" command?

In here:
https://github.com/everydayhero/boiler-room-builder/blob/master/lib/compile.js

**Comment by bradparker** [comment]
screen shot 2016-08-17 at 9 44 54 am
screen shot 2016-08-17 at 9 44 56 am
screen shot 2016-08-17 at 9 45 01 am

**Comment by alexander-bobin** [comment]
Not super clued in on webpack but this LGTM based on commits and dashboard docs :shipit:

**Pull request merged**
