### PR TITLE
Format connect logger output as json

### PR DESCRIPTION
**Pull request by bradparker**
Example: 

```
{"date":"2017-07-10 13:22:13","time":"37ms","status":"200","method":"GET","url":"/about"}
{"date":"2017-07-10 13:22:13","time":"5ms","status":"304","method":"GET","url":"/dc38dfa71b01bb8adc519a05518480d8.gif"}
{"date":"2017-07-10 13:22:13","time":"8ms","status":"200","method":"GET","url":"/main-254265067093013e0392.css"}
{"date":"2017-07-10 13:22:13","time":"12ms","status":"200","method":"GET","url":"/main-254265067093013e0392.js"}
{"date":"2017-07-10 13:22:18","time":"36ms","status":"200","method":"GET","url":"/"}
{"date":"2017-07-10 13:22:18","time":"1ms","status":"304","method":"GET","url":"/main-254265067093013e0392.js"}
{"date":"2017-07-10 13:22:18","time":"2ms","status":"304","method":"GET","url":"/main-254265067093013e0392.css"}
{"date":"2017-07-10 13:22:18","time":"6ms","status":"200","method":"GET","url":"/6c86efea2bb15496ca8d2a25c7934d63.jpg"}
```

So still to do is use a logger that doesn't default to using terminal colours.

### CODE REVIEW

**Comment by bradparker** [comment]
screen shot 2017-07-10 at 1 24 00 pm

**Comment by JonathonMA** [comment]
time -> duration

**Comment by JonathonMA** [comment]
is it url or path?

**Comment by JonathonMA** [comment]
> is it url or path?

checking our other apps for precedent now

**Comment by bradparker** [comment]
Oddly the logging middleware has both ... I have no idea what the difference is ... perhaps query / hash and such?

**Comment by bradparker** [comment]
```
{"date":"2017-07-10 13:33:25.708","duration":"1ms","status":"304","method":"GET","url":"/main-254265067093013e0392.css"}
```

@JonathonMA

**Comment by JonathonMA** [comment]
```
{"method":"GET","path":"/peter/api/v1/blueprints/8a4a1f9d-d595-5e54-a26f-ae1ef8c02f34","format":"html","controller":"Peter::BlueprintsController","action":"show","status":200,"duration":"39.60ms","view":"1.28ms","db":"15.36ms","request_id":"736730320dc6d9145af8a152d82a1605"}
```

Note that duration reports in string with explicit `ms`, which you have followed. I think we *shouldn't do this*, I think it should be a plain number, because downstream log analysis systems will be able to deal with it better. (Definitely true of kibana, I suspect true of logentries.)

Recommendations:

- [ ] omit date, as we get the log entry timestamp from the journal
- [ ] rename time to duration and emit a float in ms
- [ ] rename url to path

Unrecommendations:

- status could be served as a number instead of string, but I wouldn't, as our router logs it as a string and it's an opaque number anyway

**Comment by bradparker** [comment]
@JonathonMA so `route` for this logger is the connect / express route by the looks, so for all our stuff outputs as "Unknown". So I've renamed `url` to `path` but used the same format token.

I wanna keep the timestamp I reckon. Good context when not running in prod / staging envs

**Pull request merged**
